### PR TITLE
Updates for MorphoSource API v0.6.0

### PR DESCRIPTION
**Pull request by johnbradley**
Fixes facet filtering to use new query parameter format.
Fixes file downloading to use new returned payload format.
Adds `get_thumbnail_url()` method to `Media` object to return a URL for the thumbnail associated with the media.

### CODE REVIEW

**Review by egrace479 — COMMENTED** [review]
Everything looks good so far. Would it be possible to add an example that includes the thumbnail retrieval in context (since that was a feature Murat had requested for easier searching)?

**Comment by egrace479** [comment]
The sample thumbnail is a [blue cube](https://www.morphosource.org/assets/work-ff055336041c3f7d310ad69109eda4a887b16ec501f35afc0a547c4adb97ee72.png), could I suggest an example with a thumbnail? I have a CC0 example I could update it with?

**Comment by johnbradley** [comment]
> The sample thumbnail is a [blue cube](https://www.morphosource.org/assets/work-ff055336041c3f7d310ad69109eda4a887b16ec501f35afc0a547c4adb97ee72.png), could I suggest an example with a thumbnail? I have a CC0 example I could update it with?

Sure, feel free to change out the media ID in the README.

**Comment by johnbradley** [comment]
I guess I need to update the example output too. @egrace479 Can you tell me the media ID you are using?

**Comment by egrace479** [comment]
> I guess I need to update the example output too. @egrace479 Can you tell me the media ID you are using?

I was asking since it would be multiple suggestions. I have all the data handy, so I can just update the README directly.

**Comment by egrace479** [comment]
@johnbradley I updated the README with the media ID and associated output.

**Review by egrace479 — APPROVED** [review]
LGTM

**Review by thompsonmj — APPROVED** [review]
LGTM

**Pull request merged**
